### ISSUE TITLE
Error processing PDF: Command failed with exit code 1: ... Type3 fonts are not currently supported

### ISSUE THREAD

**Issue by jameswjesso** [mgmeyers/obsidian-zotero-integration#112]
I am coming up against this error when attempting to import a note in Obsidian.

Here is an image showing the error:

![Screen Shot 2022-10-18 at 10 19 02 AM](https://user-images.githubusercontent.com/107319330/196464432-1864b0f7-e3e1-4fee-b785-9b874b48e5da.png)

Suggestions?

**Comment by mgmeyers** [comment]
Hey @jameswjesso, unfortunately this isn't an issue I've found a workaround for yet. The problem is that the utility I use to extract text from PDF can't read one specific kind of font—Type3. This is an older font format that is still used randomly here and there by some publishers. Some users have been able to eliminate the Type3 fonts from their PDFs by printing them to a new PDF, but that can cause other issues as well.

Would you be willing to share the PDF in question? I can try poking around to see if there's anything I can do.

Also, big fan of your work!

**Comment by jameswjesso** [comment]
So I found the issue for me: Turns out it was either because of a watermark left over from a "free service" pdf editor, or from the pre-printer marks left on the edges of each page. Once those were cropped away from each page (using a paid service pdf editor), the issue was totally gone.

> Also, big fan of your work!

Thank you!!! 
This thread is such an expected place to receive that compliment and it really made my day 😊 🙏
