### ISSUE TITLE
When using Zotero group library: `Error retrieving item data: Cannot read properties of undefined '2'`

### ISSUE THREAD

**Issue by MattePalte** [mgmeyers/obsidian-zotero-integration#122]
Hi everyone, 

Most of my papers are in a `group library` of Zotero (not the default `My library`). Is there a way to specify which default library to use when importing? Since if I import a paper which is in the group library I get the following error:
`Error retrieving item data: Cannot read properties of undefined '2'`
Please let me know if I am doing anything wrong. I am new to the plugin.
Thanks in advance. I wish you a happy and productive day,
Matteo

**Comment by Ken-Adams1701** [comment]
Hi everyone,

Like Matteo, the papers that I want to export from are in a group library in Zotero. So, when I try to use the plugin I get the same error. It'd be great to be able to specify whether you're using a personal library or group library. There's a Zotero2Readwise project on PyPi that suggests how to differentiate between the two types of library: https://pypi.org/project/zotero2readwise/

Thanks,
Marc

**Comment by Innovator-X** [comment]
I am also working with Group Libraries in Zotero, and have been having similar issues to those mentioned above. Bumping in hopes that someone with a solution will notice.

**Comment by pmhb2011** [comment]
Exactly the same issue happening to me.

**Comment by Jason-Deng25** [comment]
![image](https://user-images.githubusercontent.com/74088846/213109322-8c7032c0-c8e2-4019-8681-cfaeb34d772d.png)

The same problem occurs to my PC even when I am importing files from My Library. No annotations in the pdf file can be seen in Data Explorer either!

![image](https://user-images.githubusercontent.com/74088846/213109705-88ab6ac9-954b-400a-a7f9-84bf7b2787d4.png)

**Comment by Brandkmayer** [comment]
Could this be an issue with zotero's most recent update?

**Comment by nmariano9** [comment]
Same issue here on Mac!

**Comment by Jason-Deng25** [comment]
> Could this be an issue with zotero's most recent update?

I'm using zotero 6.0.20, obsidian 1.1.9 and zotero-integration 2.2.35. Yesterday was the first day that I tried zotero-integration, so don't know if it works given another version of zotero?

**Comment by KatCe** [comment]
Hello. I am using zotero 6.0.20, obsidian 1.1.9 and zotero-integration 2.2.30. Noticed the same problem as Jason-Deng25 since some days.

**Comment by hacihabiboglu** [comment]
Same problem here! It would be great if an option was in place to extract annotations from papers on group libraries.

**Comment by idilgmrk** [comment]
I have this problem but not in a group library, on my normal library. Previously working template stopped working since december. I tried other templates that were available online and they also give the same error.

**Comment by mgmeyers** [comment]
Hi all, this should be fixed now. Update the plugin to version 2.3.0 and let me know if you run into any issues

**Comment by promethean** [comment]
@mgmeyers - I was getting the same message for the same reasons.  Just updated, but now I'm seeing 2 issues.   

1. The note is getting imported without the citekeys being respected in the Import Format Output path template.  e.g Instead of {{citekey}}/{{citekey}}.md. I'm getting a path/file called    [object Object]/[object Object].md

<img width="519" alt="snap" src="https://user-images.githubusercontent.com/545932/215315786-f5b4b9fd-b9d7-44a1-ae36-0004c6fa5c49.png">

2. The note imported with the weird filename is the correct paper, but none of the annotations (highlights, images or notes are imported). 

Hope that helps?

**Comment by promethean** [comment]
@mgmeyers - I was getting the same message for the same reasons.  Just updated, but now I'm seeing 2 issues.   

1. The note is getting imported without the citekeys being respected in the Import Format Output path template.  e.g Instead of {{citekey}}/{{citekey}}.md. I'm getting a path/file called    [object Object]/[object Object].md

<img width="519" alt="snap" src="https://user-images.githubusercontent.com/545932/215315786-f5b4b9fd-b9d7-44a1-ae36-0004c6fa5c49.png">

2. The note imported with the weird filename is the correct paper, but none of the annotations (highlights, images or notes are imported). 

Hope that helps?

**Comment by promethean** [comment]
It's ok - please ignore the above message.  I've updated to 2.3.1 and that's fixed it.  Thanks 👍
