### ISSUE TITLE
Getting duplicate highlights if external PDF reader is used

### ISSUE THREAD

**Issue by Hopsakee** [mgmeyers/obsidian-zotero-integration#128]
My highlights get duplicated if I used an external PDF annotation software. For example Adobe Acrobat.
If I make my highlights using the Zotero inbuild tool. I don't get duplicates.

I can transfer the highlights into Zotero by selecting File → “Import Annotations…” from within the Zotero PDF reader. 
After I've done that, I also get rid of the duplications.

So it seems that this marvelous extension can import the highlights from the Zotero database, but import the highlights embedded in de PDF two times.

I use an external PDF software, I would really like a solution. Maybe I messed something up in my template? My template is like this:

````
---
Year: {{date | format("YYYY")}}
tags: note/source 
Authors: {{authors}}{{directors}}
Alias: "{{title}}"
---

Title:: {{title}}
URL: {{url}}
Zotero Link: {{pdfZoteroLink}}


{% for annotation in annotations -%} 
    {%- if annotation.annotatedText -%} 
    {{annotation.annotatedText}}”{% if annotation.color %} {{annotation.colorCategory}} {{annotation.type | capitalize}} {% else %} {{annotation.type | capitalize}} {% endif %}[Page {{annotation.page}}](zotero://open-pdf/library/items/{{annotation.attachment.itemKey}}?page={{annotation.page}}&annotation={{annotation.id}}) 
    {%- endif %} 
    {%- if annotation.imageRelativePath -%}
    ![[{{annotation.imageRelativePath}}]] {%- endif %} 
{% if annotation.comment %} 
{{annotation.comment}} 
{% endif %} 
{% endfor -%}
````

**Comment by wjfeeney** [comment]
@Hopsakee - If you want to use Adobe Acrobat instead of Zotero, this is what I did to get rid of duplicates:

First, go into Acrobat preferences > Commenting > Making Comments > uncheck “Copy selected text into Highlight … comment pop-ups."

Second, mgmeyers suggests filtering your annotations to include only those that come from the Acrobat pdf, not Zotero, as follows: {% set annotations = annotations | filterby("source", "startswith", "pdf") -%}. Put that before {% for annotation in annotations -%} in your template.

**Comment by Hopsakee** [comment]
Thanks. That worked.
