### ISSUE TITLE
How to delete the footer %%Import Date%%???

### ISSUE THREAD

**Issue by Myoontyee** [mgmeyers/obsidian-zotero-integration#279]
It is part of my template
```
{% for annotation in annotations -%}
>[!Note|{{annotation.color}}]+ 
> {%- if annotation.annotatedText -%}<font color="#1f497d">**『Content』**</font> 
> >{{annotation.annotatedText}} ([{{annotation.page}}](zotero://open-pdf/library/items/{{annotation.attachment.itemKey}}?page={{annotation.page}}&annotation={{annotation.id}})){% endif %}{% if annotation.imageRelativePath %}![[{{annotation.imageRelativePath}}]]{% endif %}
>
>
{% if annotation.comment %}
{%- set line_count = 0 -%}
{%- for line in annotation.comment.split('\n') -%}
{%- if line.length > 0 -%}
{%- set line_count = line_count + 1 -%}
{%- if line_count == 1 -%}

**<font color="#1f497d">『Translation』 </font>**
{{'> > ' + line + ' \n'}}
{%- elif line_count == 2 -%}
{{'>\n' + '**<font color="#1f497d">『Note』</font>**' + ''}}
{{'> > ' + line + ' \n'}}
{%- else -%} 
{{'> > ' + line + ' \n'}}
{%- endif -%}
{%- endif -%}
{%- endfor -%}
{%- endif %}
{% endfor %}

```

Each time I use zotero integration, it import with a tail like:
```
%% Import Date: 2023-09-12T15:35:30.876+08:00 %%
```

at the same time, the persist like
```
## {{title}}

### Notes
{% persist "notes" %}
{% endpersist %}
```

after import
```
## The Boring Billion, a slingshot for Complex Life on Earth

### Notes
%% begin notes %%
%% end notes %%
```

How to delete the `%% Import Date: 2023-09-12T15:35:30.876+08:00 %%` and the `%% begin notes %%`, `%% end notes %%`??? I don't need to show it

**Comment by FeralFlora** [comment]
If you don't want:
```
%% begin notes %%
%% end notes %%
```
in your notes, delete:
```
{% persist "notes" %}
{% endpersist %}
```
Because that's what it produces. Of course, the cost is that you won't have a persistent part of the note anymore.

As is, this is always added:
`%% Import Date: 2023-09-12T15:35:30.876+08:00 %%`
There was some talk on Discord of having this removed when there is no persistence fields in the template. But if there is, it's required.

**Comment by mgmeyers** [comment]
Yes, as FeralFlora said, the import date is necessary if you use `persist`/`endpersist` but will not show up if you don't use those.

**Comment by yasirroni** [comment]
Hi, @FeralFlora 

Regarding:

> But if there is, it's required.

Zotero support batch import, so I usually just import a whole collection. When nothing changes, even if there is persist, I would prefer the "%% Import Date: 2023-09-12T15:35:30.876+08:00 %%" is not updated (or always removed). That is because I also use git to track changes. Manually import one file to avoid "updating" all unchanged notes is littering the git.
