### ISSUE TITLE
"Persist" duplicates annotations at the end of the note, instead of only adding new annotations

### ISSUE THREAD

**Issue by sulth1** [mgmeyers/obsidian-zotero-integration#335]
Hello,

I am new to all of this, so I probably made a mistake somewhere.
I am trying to find a way to only import new annotations (from Zotero) into the current Obsidian note, without losing all the writing done in the Obsidian note. After some reasearch, it seems doable with a “persist” tag. https://github.com/mgmeyers/obsidian-zotero-integration/issues/282#issuecomment-1722376403

When I re-import after having made new annotations in Zotero, my writing done in Obsidian is indeed kept. However, it duplicates all the annotations at the end of the note, instead of only the new ones.

Not knowing how to do, I simply put the {% persist "notes" %} at the very beginning and the {% endpersist %} at the very end.

Here is my template (from Bryan Jenks):

```
---
tags:
status:
Title: {{title}}
Year: {{date | format("YYYY")}}
Authors: {{authors}}{{directors}}
citekeys: {{citekey}}
keywords: {{allTags}}
related: {{relation.citekey}} 
---
{% persist "notes" %}
>[!abstract]-
>URL: {{url}}
>Zotero Link: {{pdfZoteroLink}}
>
>{{abstractNote}}

## Notes

> [!info]-
| <mark class="hltr-grey">Highlight Color</mark> | Meaning                       |
| ---------------------------------------------- | ----------------------------- |
| <mark class="hltr-red">Red</mark>              | Disagree with Author          |
| <mark class="hltr-orange">Orange</mark>        | Important Point By Author     |
| <mark class="hltr-yellow">Yellow</mark>        | Interesting Point             |
| <mark class="hltr-green">Green</mark>          | Important To Me               |
| <mark class="hltr-blue">Blue</mark>            | Notes After Initial Iteration |
| <mark class="hltr-purple">Purple</mark>        | Literary Note To Lookup Later |


{% for annotation in annotations -%}
    {%- if annotation.annotatedText -%} 
		- <mark class="hltr-{{annotation.colorCategory | lower}}">"{{annotation.annotatedText | escape}}”</mark> [Page {{annotation.page}}](zotero://open-pdf/library/items/{{annotation.attachment.itemKey}}?page={{annotation.page}}&annotation={{annotation.id}})
    {%- endif %} 
    {%- if annotation.imageRelativePath -%}
    ![[{{annotation.imageRelativePath}}]] {%- endif %} 
{% if annotation.comment %} 
{{annotation.comment}} 
{% endif %} 
{% endfor -%}

## References to check out

## Other

{% endpersist %}

```

Thank you in advance for the help.

**Comment by FeralFlora** [comment]
First of, you shouldn't have one persist for your whole template, because there are different needs in each situation.

I've explained how to use persist [here](https://discord.com/channels/686053708261228577/1156633421922181201/1176978390008471744) in the #academic-tools channel of the Obsidian Discord server, so I'll just copy and paste that here:

---

Basically, `{% persist "notes" %}` in the template becomes `%% begin notes %%` in the output. This marks the start of a section that will not be overwritten. Similarly, `{% endpersist %}` becomes `%% end notes %%`, which signifies where the persistent section ends. "notes" in this example is just a name, it doesn't connect to any data or anything like that. So you can name your persistent sections whatever you want. 

Everything between the beginning and end of the persistent section is protected from overwriting—and thus also from updating. That means that if you use a persistent section around your annotations, new annotations or annotation changes will not be reflected within the persistent section, but will be appended below.

For static sections like a general area to write notes, you'll want to use `{%- if isFirstImport %}` like so:

```
{% persist "notes" -%}
{%- if isFirstImport %}

YOUR CONTENT

{% endif %}{% endpersist %}
```

Without `isFirstImport`, a new "notes" section will be added every time you update.

For your annotations, you'll want to ensure that only new annotations are appended, otherwise you will get a full set of annotations added every import. You can do this like so:

```
{% persist "annotations" %}
{% set annotations = annotations | filterby("date", "dateafter", lastImportDate) -%}
{% if annotations.length > 0 %}

OTHER ANNOTATION FORMATTING AND CLOSING IF AND PERSIST
```

This filters the set of annotations down to those that have a date which is after the last import date.
