### ISSUE TITLE
pdf extraction fails

### ISSUE THREAD

**Issue by ibagur** [mgmeyers/obsidian-zotero-integration#59]
Hi,

I am trying to use the plugin to extract several highlights from a PDF paper, done before with Zotero. No matter what, it seems to fail and I get the following error, and I do not know how to solve it:

´Error processing PDF: Command failed with exit coder 1:
... (in here, several paths and other stuff I do not know)
Type3 fonts are not currently supported (feature not currently supported)´

As the error appears on a floating windows, and it is impossible to cut and paste the text, I better attach a screenshot.

Thanks.

<img width="317" alt="Screenshot 2022-05-29 at 18 40 03" src="https://user-images.githubusercontent.com/2979615/170881732-82b6df8f-ca21-4ccd-89cf-76250580450c.png">

**Comment by andrewcrook** [comment]
I would first try this assuming its a Tesseract OCR issue recognising these fonts

Does disabling OCR for images make a difference?
<img width="736" alt="image" src="https://user-images.githubusercontent.com/803618/171169034-5f28e65e-3b18-4ad8-bb8f-4926e66d862c.png”>
This will make images import as images without text into Obsidian 

Otherwise

Does the PDF include text data? 
If not try a tool to convert PDF to PDF+text i.e third party OCR

**Comment by mgmeyers** [comment]
Hi @ibagur, @andrewcrook is almost correct.

The issue here is that your PDF uses a type of font that is no longer widely supported. There isn't a whole lot I can do about this because of technical limitations. You can try searching around for tools to convert type 3 PDF fonts to type 1. Here's one approach, for example: https://me.net.nz/post/type3fonts/

**Comment by andrewcrook** [comment]
@kitaev-chen 

Hi, It seems it might not be or just be the OCR utility Tesseract that has this issue.

This plugin installs a utility called [pdfannots2json](https://github.com/mgmeyers/pdfannots2json)
Looking at this source code of this go based app I see that it uses a library called [unipdf](https://github.com/unidoc/unipdf). Which also handles text extraction. 

Looking through issues I found an [issue claiming that it isn't compatible with "Type3 fonts”](https://github.com/unidoc/unipdf/issues/37). They believe compatibility could be implemented but I didn’t see a time scale or intention. 

A PDF document’s text can seem to be using Type 1 fonts but may use Type 3 fonts in figures (diagrams).
Type 3 fonts are not popular and considered old, from the PostScript days,  it is [recommended not to use them.](https://www.prepressure.com/fonts/basics/type3)

> Adobe even admitted that recent versions of its RIPs may be incompatible with some very old Type 3 fonts. Fortunately Type 3 fonts are hardly used anymore so I would not worry too much about them.

You are correct though, if you meant, zotfile it can extract the text. So maybe there is the clue to making this work in the future, who knows?

Personally, I would look at ways to convert any PDFs with Type 3 fonts to rid of them.
