### ISSUE TITLE
[Bug] Citation autocomplete feature doesn't work

### ISSUE THREAD

**Issue by EhuddR** [mgmeyers/obsidian-zotero-integration#68]
The fix doesn't work. I don't have any suggestions from zotero when i hhit the @ key nor any error messages it just doesn't do anything.

_Originally posted by @EhuddR in https://github.com/mgmeyers/obsidian-zotero-integration/issues/49#issuecomment-1171429465_

**Comment by mgmeyers** [comment]
@EhuddR would you mind exporting your library as better CSL JSON and uploading it here? Might help me debug what's going on here.

<img width="481" alt="Screen Shot 2022-06-30 at 12 47 40 PM" src="https://user-images.githubusercontent.com/2694747/176764447-786e0e57-641d-46f1-a3d8-3cad5d6de060.png">

<img width="371" alt="Screen Shot 2022-06-30 at 12 47 58 PM" src="https://user-images.githubusercontent.com/2694747/176764501-8fb6bfd8-2c22-4194-a946-ed467ba14fc5.png">

**Comment by EhuddR** [comment]
[Mi biblioteca.tar.gz](https://github.com/mgmeyers/obsidian-zotero-integration/files/9023994/Mi.biblioteca.tar.gz)

Thank you very much for your assistance. I hope you can discover what I'm doing wrong

**Comment by mgmeyers** [comment]
Hmm, strange. Your library looks right. What version of the Better Bibtex plugin are you on?

**Comment by EhuddR** [comment]
Better Bibtex 6.7.15
Obsidian 14.15
OS. EndeavourOS Arch Linux x86_64
Kernel: 5.18.7-arch1-1

I have the next console error

![image](https://user-images.githubusercontent.com/78237982/177013215-553c2738-a1ac-4803-b6bd-370888603a03.png)

**Comment by mgmeyers** [comment]
@EhuddR one user reported fixing this by uninstalling better bibtext and reinstalling it. Could you give that a try?

**Comment by EhuddR** [comment]
> @EhuddR one user reported fixing this by uninstalling better bibtext and reinstalling it. Could you give that a try?

Hi! I have recently reinstall the Better Bibtex plugin V.6.7.17, but still not workin. 
![image](https://user-images.githubusercontent.com/78237982/180704452-431885a4-4453-4d87-9f2b-7491d7633152.png)

**Comment by alltagsverstand** [comment]
Just to confirm that citekey autocompletion isn't working for me, too. BetterBibtex settings checked, also tried to uninstall and reinstall BetterBibtex.

**Comment by alltagsverstand** [comment]
Any news on this or any idea what's causing this? Still not working...

**Comment by EhuddR** [comment]
I've given up hope, this has never worked for me :cry:

**Comment by MSBack** [comment]
The autocompletion dialogue used to work for me, but now I'm having the same issue, nothing shows up at all. 

Actually, as I was writing this, I check Zotero for BetterBibtex updates, and there happened to be one. I updated, and now the dialogue shows up again, but the search is quite bad and inconsistent. It doesn't list all the relevant citations, and doesn't find them consistently when listed.

Here, I just typed `@o` and scrolled down to find `@Oreskes.Conway2010DefeatingMerchantsDoubt`.
![image](https://user-images.githubusercontent.com/33608083/222849292-9c5c9484-f43b-42f9-a269-9a46ee68c0af.png)

Now, if I type `@or`, I just get this:
![image](https://user-images.githubusercontent.com/33608083/222849634-37fed368-8dda-40ed-80bc-150a1e38f153.png)

If I type `@oreskes` quickly, it get no dropdown at all:
![image](https://user-images.githubusercontent.com/33608083/222849842-d89d7865-10cf-46a0-a472-980716846526.png)

I have another citation in Zotero called `@Rudloff.etal2022BeliefsNatureKnowledge`, which I can import as a Literature note using Zotero Integration. But if I try to cite it, the autocomplete dialogue cannot find it at all.

If I just type `@r` and scroll down, the list only goes down to citekeys that start with `@re`. If I type `@rudkoff`, no dialogue shows up.
![image](https://user-images.githubusercontent.com/33608083/222851463-f68266a9-443e-4c90-96ad-ae0e7e88383b.png)

Just to be clear, for each search, I am typing from the beginning, because otherwise, the dialogue is known to not show up, so that's not the problem.

**Comment by MSBack** [comment]
It seems to be that there is some case-sensitivity issue, because `@Rudloff` works as expected, but `@rudloff` does not.

![Obsidian_lEePmq6iHX](https://user-images.githubusercontent.com/33608083/222852536-3007cc1c-0375-415c-abf5-5b56853c78ae.gif)

**Comment by MSBack** [comment]
After updating BetterBibtex again today, the autocomplete dialogue now behaves as expected and there is no case-sensitivity issue.

**Comment by MSBack** [comment]
Update: Autocomplete stopped working for me in my main vault, but it works when testing it in a test vault, so it might be some adverse interaction with another plugin.

**Comment by MSBack** [comment]
@mgmeyers Are you working on this? Do you need any debugging done? Logs? I can help as requested.

**Comment by ashley681** [comment]
Yeah， I have the same problem.

**Comment by ashley681** [comment]
I also have another problem.  The citation key [@lowerauthor,year] in my Obsidian document used to be modifiable by clicking on the citation, however it doesn't work these days. I can't fix it.

**Comment by MSBack** [comment]
It turns out that my issue with citekey autocompletion was caused by interference by the Completr plugin. It's regex overrides Zotero Integrations's.

**Comment by alltagsverstand** [comment]
Just to assure that in my case it's not caused by conflicts with any other plugin - citekey autocompletion doesn't work even when all plugins except zotero integration are turned off.

**Comment by LamFTS** [comment]
I encountered the similar issue, when i hit @, there is a menu flash across, but it disappeared soon before the citation suggestion show up. I think that may help dig into the problem.
My OS: Archlinux x64 6.1.38-1-lts
Zotero: 6.026
Better BibTex: v6.7.94
Zotero Integration : 3.0.3
![image](https://github.com/mgmeyers/obsidian-zotero-integration/assets/53118840/ba289b1f-4bbf-4550-bf80-4bc6616081d8)

**Comment by Comprehensive-Jason** [comment]
Was citekey autocomplete removed in a recent update? I can't seem to find it in settings anymore.
![image](https://github.com/mgmeyers/obsidian-zotero-integration/assets/68677082/432e3a0d-93eb-4cf5-b22a-f300c8911dc6)

I totally understand if the maintenance of the feature was too time-consuming. I also get it if this is just temporary to prevent more issues.

**Comment by MSBack** [comment]
> Was citekey autocomplete removed in a recent update? I can't seem to find it in settings anymore.

Yes, the feature has been moved to the Pandoc Reference List plugin. This was announced on the Obsidian Discord.

**Comment by Comprehensive-Jason** [comment]
Gotcha. I presume this FR needs to be moved over there then?

**Comment by MSBack** [comment]
> Gotcha. I presume this issue needs to be moved over there then?

Yeah, I guess so.
